### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by EmreOzkose** [tridivb/Epic_Kitchens_Feature_Extractor_Detectron#8]
Could you share any pre-trained model? 

There is a model in Python2 branch, but I got irrelevant results like 
![image](https://github.com/tridivb/Epic_Kitchens_Object_Detector_Detectron/assets/17765576/d59ff7d8-42ab-4fd7-af5b-637a16112bf0)

Is there any other trained model ?

**Comment by tridivb** [comment]
HI Emre, I don't have access to the weights anymore. Sorry! It might be helpful to look for some more updated models as well as the dataset has had some significant changes, since I worked on it.
